package joserodpt.realskywars.plugin.managers;

/*
 *   _____            _  _____ _
 *  |  __ \          | |/ ____| |
 *  | |__) |___  __ _| | (___ | | ___   ___      ____ _ _ __ ___
 *  |  _  // _ \/ _` | |\___ \| |/ / | | \ \ /\ / / _` | '__/ __|
 *  | | \ \  __/ (_| | |____) |   <| |_| |\ V  V / (_| | |  \__ \
 *  |_|  \_\___|\__,_|_|_____/|_|\_\\__, | \_/\_/ \__,_|_|  |___/
 *                                   __/ |
 *                                  |___/
 *
 * Licensed under the MIT License
 * @author José Rodrigues © 2019-2025
 * @link https://github.com/joserodpt/RealSkywars
 */

import joserodpt.realskywars.api.RealSkywarsAPI;
import joserodpt.realskywars.api.config.RSWConfig;
import joserodpt.realskywars.api.config.TranslatableLine;
import joserodpt.realskywars.api.managers.LobbyManagerAPI;
import joserodpt.realskywars.api.player.RSWPlayer;
import joserodpt.realskywars.api.player.RSWPlayerItems;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Player;

public class LobbyManager extends LobbyManagerAPI {

    public RealSkywarsAPI rsa;

    public LobbyManager(RealSkywarsAPI rsa) {
        this.rsa = rsa;
    }

    private Location lobbyLOC;
    private Location waitingLobbyLOC;
    private Boolean loginTP = true;

    @Override
    public void loadLobby() {
        this.loginTP = RSWConfig.file().getBoolean("Config.Auto-Teleport-To-Lobby");
        if (RSWConfig.file().isSection("Lobby")) {
            double x = RSWConfig.file().getDouble("Lobby.X");
            double y = RSWConfig.file().getDouble("Lobby.Y");
            double z = RSWConfig.file().getDouble("Lobby.Z");
            float yaw = RSWConfig.file().getFloat("Lobby.Yaw");
            float pitch = RSWConfig.file().getFloat("Lobby.Pitch");
            World world = Bukkit.getServer().getWorld(RSWConfig.file().getString("Lobby.World"));
            this.lobbyLOC = new Location(world, x, y, z, yaw, pitch);
        }

        this.loadWaitingLobby();
    }

    @Override
    public void loadWaitingLobby() {
        this.waitingLobbyLOC = null;

        if (!RSWConfig.file().isSection("Waiting-Lobby")) {
            return;
        }

        String worldName = RSWConfig.file().getString("Waiting-Lobby.World");
        if (worldName == null) {
            return;
        }

        //the waiting lobby world is generated by RealSkywars, so the server won't load it on its own
        World world = Bukkit.getServer().getWorld(worldName);
        if (world == null) {
            rsa.getWorldManagerAPI().loadWorld(worldName, World.Environment.NORMAL);
            world = Bukkit.getServer().getWorld(worldName);
        }

        if (world == null) {
            rsa.getLogger().warning("Could not load the waiting lobby world " + worldName + ". Rooms with manual team selection cannot be joined until it exists - recreate it with /rsw createwaitinglobby.");
            return;
        }

        //WorldManager#loadWorld is tuned for map worlds (autosave off, pvp on) - a hand built lobby needs the opposite
        world.setAutoSave(true);
        world.setPVP(false);

        double x = RSWConfig.file().getDouble("Waiting-Lobby.X");
        double y = RSWConfig.file().getDouble("Waiting-Lobby.Y");
        double z = RSWConfig.file().getDouble("Waiting-Lobby.Z");
        float yaw = RSWConfig.file().getFloat("Waiting-Lobby.Yaw");
        float pitch = RSWConfig.file().getFloat("Waiting-Lobby.Pitch");
        this.waitingLobbyLOC = new Location(world, x, y, z, yaw, pitch);
    }

    @Override
    public void tpToLobby(Player player) {
        if (this.lobbyLOC != null && player != null) {
            try {
                player.teleport(this.lobbyLOC);
            } catch (Exception e) {
                rsa.getLogger().warning("Error while teleporting player to lobby: " + e.getMessage());
            }
        }
    }

    @Override
    public void tpToLobby(RSWPlayer p) {
        if (this.lobbyLOC != null && p != null) {
            tpToLobby(p.getPlayer());
            TranslatableLine.LOBBY_TELEPORT.send(p, true);
            RSWPlayerItems.LOBBY.giveSet(p);
        } else {
            TranslatableLine.LOBBY_NOT_SET.send(p, true);
        }
    }

    @Override
    public Location getLobbyLocation() {
        return this.lobbyLOC;
    }

    @Override
    public boolean scoreboardInLobby() {
        return RSWConfig.file().getBoolean("Config.Scoreboard-In-Lobby");
    }

    @Override
    public void setLobbyLoc(Location location) {
        this.lobbyLOC = location;
        //give everyone items again

        for (Player p : location.getWorld().getPlayers()) {
            RSWPlayer rswPlayer = rsa.getPlayerManagerAPI().getPlayer(p);
            if (rswPlayer != null) {
                RSWPlayerItems.LOBBY.giveSet(rswPlayer);
            }
        }
    }

    @Override
    public boolean tpLobbyOnJoin() {
        return loginTP && this.lobbyLOC != null;
    }

    @Override
    public boolean isInLobby(World w) {
        if (w == null || this.lobbyLOC == null || this.lobbyLOC.getWorld() == null) {
            return false;
        }
        return this.lobbyLOC != null && this.lobbyLOC.getWorld().equals(w);
    }

    @Override
    public Location getWaitingLobbyLocation() {
        return this.waitingLobbyLOC;
    }

    @Override
    public void setWaitingLobbyLoc(Location location) {
        this.waitingLobbyLOC = location;
    }

    @Override
    public boolean isWaitingLobbyReady() {
        //getWorld() goes null if the world was never created, failed to load on startup, or was
        //unloaded after the fact - the location alone is not proof there is anywhere to stand.
        return this.waitingLobbyLOC != null && this.waitingLobbyLOC.getWorld() != null;
    }

    @Override
    public boolean tpToWaitingLobby(RSWPlayer p) {
        if (this.waitingLobbyLOC == null || p == null || p.getPlayer() == null) {
            return false;
        }

        try {
            p.teleport(this.waitingLobbyLOC);
            TranslatableLine.WAITING_LOBBY_TELEPORT.send(p, true);
            return true;
        } catch (Exception e) {
            rsa.getLogger().warning("Error while teleporting player to the waiting lobby: " + e.getMessage());
            return false;
        }
    }

    @Override
    public boolean isInWaitingLobby(World w) {
        if (w == null || this.waitingLobbyLOC == null || this.waitingLobbyLOC.getWorld() == null) {
            return false;
        }
        return this.waitingLobbyLOC.getWorld().equals(w);
    }

}
